name: CI/CD - Deploy PHP Application to IIS in VirtualBox

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the latest code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install MSDeploy (optional, if not already installed)
    - name: Install MSDeploy
      run: |
        Install-WindowsFeature -Name Web-Server, Web-Mgmt-Service
        $msdeployUrl = "https://download.microsoft.com/download/E/2/3/E234C7BC-9C3F-4E7D-8D50-FBC7847243FA/msdeploy.exe"
        $msdeployPath = "$env:USERPROFILE/msdeploy.exe"
        Invoke-WebRequest -Uri $msdeployUrl -OutFile $msdeployPath
        Start-Process -FilePath $msdeployPath -ArgumentList "/quiet", "/passive" -Wait

    # Step 3: Deploy the code to IIS in VirtualBox environment
    - name: Deploy to IIS in VirtualBox
      run: |
        $ErrorActionPreference = "Stop"
        .\msdeploy.exe -verb:sync `
                      -source:contentPath="." `
                      -dest:contentPath="C:\inetpub\wwwroot\your_site"
      env:
        DEPLOY_PATH: "C:\inetpub\wwwroot\your_site"

    # Step 4: Restart IIS to apply the changes (if needed)
    - name: Restart IIS
      run: |
        iisreset
